"""empty message

Revision ID: 6f2e92bdbe48
Revises: 
Create Date: 2022-10-16 01:32:50.165191

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f2e92bdbe48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_storage',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('long_url', sa.TEXT(), nullable=False),
    sa.Column('short_url', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_storage_long_url'), 'url_storage', ['long_url'], unique=True)
    op.create_index(op.f('ix_url_storage_short_url'), 'url_storage', ['short_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_storage_short_url'), table_name='url_storage')
    op.drop_index(op.f('ix_url_storage_long_url'), table_name='url_storage')
    op.drop_table('url_storage')
    # ### end Alembic commands ###
